# Generated by Django 2.2.4 on 2020-05-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('kod_of_auditory', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_auditory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day_of_week',
            fields=[
                ('kod_raspisania', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('kod_of_discipline', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_discipline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('kod_of_group', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pair_number',
            fields=[
                ('kod_of_pair', models.AutoField(primary_key=True, serialize=False)),
                ('pair_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('kod_of_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('kod_of_raspisanie', models.AutoField(primary_key=True, serialize=False)),
                ('parity', models.BooleanField()),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Auditory')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Day_of_week')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Group')),
                ('pair_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Pair_number')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('kod_of_raspisanie', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_change', models.DateField()),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Auditory')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Day_of_week')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raspisanie.Teacher')),
            ],
        ),
    ]
