# Generated by Django 2.2.4 on 2020-05-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspisanie',
            name='obe_nedeli',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
