# Generated by Django 2.2.4 on 2020-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspisanie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_semestr_date',
            fields=[
                ('kod_of_date', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
